import Image from "next/image";
import Link from "next/link";

export default function About() {
  return (
    <div style={{ paddingTop: "60px", minHeight: "100vh", backgroundColor: "#0A0A0A" }}>

      {/* Hero Section - Whisper Quiet */}
      <div style={{
        maxWidth: "900px",
        margin: "0 auto",
        padding: "clamp(20px, 4vh, 40px) 24px clamp(60px, 10vh, 80px)",
        textAlign: "center"
      }}>
        <h1 style={{
          fontFamily: "Playfair Display, Georgia, serif",
          fontSize: "clamp(36px, 5vw, 48px)",
          fontWeight: 300,
          color: "#FAFAF8",
          marginBottom: "clamp(16px, 2vh, 20px)",
          letterSpacing: "0.02em",
          lineHeight: 1.1
        }}>
          Daniel Wahnich
        </h1>
        <p style={{
          fontFamily: "Playfair Display, Georgia, serif",
          fontSize: "clamp(16px, 2vw, 20px)",
          fontStyle: "italic",
          fontWeight: 300,
          color: "#CCCCCC",
          letterSpacing: "0.15em",
          marginBottom: "clamp(32px, 5vh, 48px)"
        }}>
          Ostinato Rigore
        </p>
        <p style={{
          fontFamily: "Playfair Display, Georgia, serif",
          fontSize: "clamp(18px, 2.5vw, 24px)",
          fontWeight: 300,
          color: "#FAFAF8",
          letterSpacing: "0.05em",
          lineHeight: 1.4
        }}>
          Artist, Autodidact, Builder
        </p>
      </div>

      {/* Subtle Divider - White */}
      <div style={{
        width: "1px",
        height: "40px",
        backgroundColor: "#FAFAF8",
        margin: "0 auto clamp(50px, 8vh, 70px)"
      }} />

      {/* About Me - Builder Section */}
      <div style={{
        maxWidth: "720px",
        margin: "0 auto",
        padding: "0 24px clamp(60px, 10vh, 80px)"
      }}>
        <h2 style={{
          fontSize: "clamp(11px, 1.4vw, 13px)",
          fontWeight: 500,
          letterSpacing: "0.25em",
          textTransform: "uppercase",
          color: "#FAFAF8",
          marginBottom: "clamp(48px, 8vh, 64px)",
          textAlign: "center"
        }}>
          About Me
        </h2>

        <div style={{
          display: "flex",
          flexDirection: "column",
          gap: "clamp(32px, 5vh, 48px)"
        }}>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            Deciding to build this website was my way of showing my work, my progress, and what I'm capable of, or better said, what I'm still figuring out every single day. I'm a solo builder, self-taught, never educated by humans in the formal sense.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            LLMs were literally the technology that changed my life the most. They gave me the tools to teach myself anything my heart wanted to understand. The beauty of it is that there's no person on the other side judging my pace, my curiosity, or the strange routes I take to find the truth.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            My mission in the coming years is simple: to master AI. And I'm grateful for the brilliant minds who built these systems, the ones who simplified the complexity just enough for someone like me to climb the mountain.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            My code is 100% generated by LLMs, the implementation is mine. I used to hear people say LLMs aren't capable of producing 100% of the code, blah blah. They definitely are. It's just far from as easy as it sounds. It takes a long, iterative process of refining, validating, and stress-testing until the final script is solid.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            I don't use low-code tools, and I don't let AI "fix" or adjust my work afterward. The only thing I use these models for is generating the raw code itself. GPT is incredible for reasoning, and Claude delivers the strongest code. That combination became my pipeline.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            I don't pretend to be a mathematician or an engineer. I'm just a very curious individual with the ability to learn fast. Everything you see on this website is work I built on my own, experiments, projects, and attempts to understand how to speak with the machine and bring my thoughts onto the screen.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            This is my path.
          </p>
        </div>
      </div>

      {/* Vertical Divider - White */}
      <div style={{
        width: "1px",
        height: "50px",
        backgroundColor: "#FAFAF8",
        margin: "clamp(60px, 10vh, 80px) auto"
      }} />

      {/* Main Story - Authentic Voice */}
      <div style={{
        maxWidth: "720px",
        margin: "0 auto",
        padding: "0 24px clamp(60px, 10vh, 80px)"
      }}>
        <div style={{
          display: "flex",
          flexDirection: "column",
          gap: "clamp(32px, 5vh, 48px)"
        }}>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            My path wasn't linear, not even close. I started in retail, working with people every day, trying to understand them. Someone I admired once told me: "Your soul is walking around the world looking for precision." I didn't fully understand it then, but I lived it. I suffered from it. I searched for it everywhere.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            That search eventually led me into a darker phase. I became manipulative, not out of cruelty, but out of obsession. I kept testing people, pushing them, trying to understand the boundaries of truth, loyalty, intention. And as I did, I lost people one by one.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            I eventually learned something important: Humans are variables. Each person holds their own definition of precision, their own worldview, their own logic. There is no universal alignment in human nature. Ironically, that made the sentence, the one that followed me for years, lose its meaning. And that's what changed everything.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            Because I finally found precision somewhere else. I found it in code.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            In software, I discovered the only medium that can "lock" a thought, a pattern, forever. Something that doesn't misunderstand, doesn't shift, doesn't betray its logic. A place where years of life experience can compress into a function, a system, an architecture. Where structure is a language. Where clarity is possible.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            In mathematics, the word manipulation isn't an insult. It's the definition of transformation, shaping something until it reveals truth. Once I understood that, I stopped hating myself for being "manipulative." It was simply my way of trying to understand how things work.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            Since then, everything changed.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            And somewhere along this journey, I realized something else: I am an artist. Not in the traditional sense, but in the sense that every human being creates. Ideas, patterns, systems, meaning. A sentence by Albert Einstein connected deeply with me: "Art is intelligence having fun." It gave me confidence. To stop seeking approval. To clear my mind. To create whatever my thoughts and heart desire. That, to me, is art.
          </p>
        </div>
      </div>

      {/* Vertical Divider - White */}
      <div style={{
        width: "1px",
        height: "50px",
        backgroundColor: "#FAFAF8",
        margin: "clamp(60px, 10vh, 80px) auto"
      }} />

      {/* Philosophy Section */}
      <div style={{
        maxWidth: "720px",
        margin: "0 auto",
        padding: "0 24px clamp(60px, 10vh, 80px)"
      }}>
        <h2 style={{
          fontSize: "clamp(11px, 1.4vw, 13px)",
          fontWeight: 500,
          letterSpacing: "0.25em",
          textTransform: "uppercase",
          color: "#FAFAF8",
          marginBottom: "clamp(48px, 8vh, 64px)",
          textAlign: "center"
        }}>
          Philosophy, Thought & Identity
        </h2>

        <div style={{
          display: "flex",
          flexDirection: "column",
          gap: "clamp(32px, 5vh, 48px)"
        }}>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            Another person I appreciate deeply introduced me to a famous sentence by René Descartes: "Cogito ergo sum", "I think, therefore I am." It took time to sink in. She didn't explain it, she simply said it to me and left the meaning for me to discover.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            Understanding this quote, or at least what I believe I understand, affects me in two opposite ways: On one side, it brings relief. On the other, it brings fear. I doubt every thought except the thought itself. That's the one thing that cannot be denied.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            Later, I named my company CogitoErgoSum, and I even tattooed it on my body. I'm not sure how I'll feel about that in the future, tattoos for me are a strange relationship of love and hate, but the meaning stayed.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            I'm also still a big admirer of Sigmund Freud, even though modern thinkers like to "cancel" him. His teachings make sense to me, especially his theory of personality, the idea that the ego acts as the administrator of the mind. It helped me understand myself more than any self-help book ever could.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            Another sentence that shaped me is by Leonardo da Vinci: "Ostinato Rigore", "Persistent Rigour." I learned it recently, reading someone I truly admire. When I was eighteen, I trusted him enough to tattoo another word he once gave me, "Veritas" (truthfulness). He abandoned the sentence, but I never did.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            "Ostinato Rigore" aligned with me immediately. It became my motto. Don't worry, I'm not planning to tattoo it. I'm probably done with tattoos… at least for now.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            I don't know much. Most days, I feel like I don't know anything at all, only that there is an entire universe left to learn. Time… well, it terrifies me every time I think about it. The speed of it. The weight of it. The fact that it never stops.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            But the one thing that excites me every single day, the thing that fulfills me more than anything, is learning. Understanding something today that I didn't understand yesterday. Getting wiser, even in tiny increments. Growing to the point I sometimes forget I'm supposed to make a living.
          </p>
          <p style={{
            fontSize: "clamp(16px, 2vw, 18px)",
            color: "#FAFAF8",
            lineHeight: 1.9,
            fontWeight: 300,
            letterSpacing: "0.01em"
          }}>
            And maybe that's okay. Maybe curiosity is the living.
          </p>
        </div>
      </div>

      {/* Vertical Divider - White */}
      <div style={{
        width: "1px",
        height: "50px",
        backgroundColor: "#FAFAF8",
        margin: "clamp(60px, 10vh, 80px) auto"
      }} />

      {/* Read Full Life Story Link */}
      <div style={{
        maxWidth: "700px",
        margin: "0 auto",
        padding: "0 24px clamp(48px, 8vh, 64px)",
        textAlign: "center"
      }}>
        <Link href="/story" style={{
          fontSize: "clamp(14px, 1.8vw, 15px)",
          color: "#FAFAF8",
          textDecoration: "none",
          borderBottom: "1px solid #666666",
          paddingBottom: "3px",
          letterSpacing: "0.02em",
          fontStyle: "italic"
        }}>
          Read full life story
        </Link>
      </div>

      {/* Vertical Divider - White */}
      <div style={{
        width: "1px",
        height: "50px",
        backgroundColor: "#FAFAF8",
        margin: "clamp(60px, 10vh, 80px) auto"
      }} />

      {/* Contact - Minimal */}
      <div style={{
        maxWidth: "700px",
        margin: "0 auto",
        padding: "0 24px clamp(60px, 10vh, 80px)",
        textAlign: "center"
      }}>
        <h2 style={{
          fontSize: "clamp(11px, 1.4vw, 13px)",
          fontWeight: 500,
          letterSpacing: "0.25em",
          textTransform: "uppercase",
          color: "#FAFAF8",
          marginBottom: "clamp(48px, 8vh, 64px)"
        }}>
          Contact
        </h2>
        <p style={{
          fontSize: "clamp(15px, 1.9vw, 17px)",
          color: "#FAFAF8",
          marginBottom: "clamp(24px, 4vh, 32px)",
          letterSpacing: "0.01em"
        }}>
          <a href="mailto:cogitoergosum143@gmail.com" style={{
            color: "#FAFAF8",
            textDecoration: "none",
            borderBottom: "1px solid #666666",
            paddingBottom: "2px"
          }}>
            cogitoergosum143@gmail.com
          </a>
        </p>
        <p style={{
          fontSize: "clamp(15px, 1.9vw, 17px)",
          color: "#FAFAF8",
          letterSpacing: "0.01em"
        }}>
          <a href="https://github.com/manfromnowhere143" target="_blank" rel="noopener noreferrer" style={{
            color: "#FAFAF8",
            textDecoration: "none",
            borderBottom: "1px solid #666666",
            paddingBottom: "2px"
          }}>
            GitHub
          </a>
        </p>
      </div>

      {/* Final Statement - Descartes Quotes */}
      <div style={{
        backgroundColor: "#000000",
        padding: "clamp(100px, 15vh, 140px) 24px"
      }}>
        <div style={{ maxWidth: "800px", margin: "0 auto", textAlign: "center" }}>
          {/* First Quote */}
          <p style={{
            fontFamily: "Playfair Display, Georgia, serif",
            fontSize: "clamp(20px, 3.5vw, 30px)",
            fontStyle: "italic",
            fontWeight: 300,
            color: "#FAFAF8",
            lineHeight: 1.6,
            letterSpacing: "0.01em",
            marginBottom: "12px"
          }}>
            "Cogito, ergo sum"
          </p>
          <p style={{
            fontSize: "clamp(14px, 2vw, 17px)",
            fontWeight: 300,
            color: "#FAFAF8",
            letterSpacing: "0.02em",
            marginBottom: "clamp(48px, 7vh, 64px)"
          }}>
            I think, therefore I am
          </p>

          {/* Second Quote */}
          <p style={{
            fontFamily: "Playfair Display, Georgia, serif",
            fontSize: "clamp(20px, 3.5vw, 30px)",
            fontStyle: "italic",
            fontWeight: 300,
            color: "#FAFAF8",
            lineHeight: 1.6,
            letterSpacing: "0.01em",
            marginBottom: "12px"
          }}>
            "Dubito, ergo cogito, ergo sum"
          </p>
          <p style={{
            fontSize: "clamp(14px, 2vw, 17px)",
            fontWeight: 300,
            color: "#FAFAF8",
            letterSpacing: "0.02em",
            marginBottom: "clamp(40px, 6vh, 56px)"
          }}>
            I doubt, therefore I think, therefore I am
          </p>

          {/* Attribution */}
          <p style={{
            fontSize: "12px",
            color: "#FAFAF8",
            letterSpacing: "0.2em",
            textTransform: "uppercase"
          }}>
            René Descartes
          </p>
        </div>
      </div>

    </div>
  );
}
